<script setup>
import { ref } from 'vue';

// State for the mobile dropdown
const isMenuOpen = ref(false);

const navLinks = [
    { name: 'Tasks', path: '/' },
    { name: 'Auth', path: '/auth' }
];
</script>

<template>
    <nav class="navbar">
        <div class="navbarContainer">
            <!-- LOGO -->
            <div class="logo">
                <router-link to="/">
                    <img src="../assets/logo-with-text.svg" alt="Logo">
                </router-link>
            </div>

            <!-- DESKTOP MENU (Hidden on Mobile) -->
            <div class="desktopMenu">
                <ul class="navList">
                    <li v-for="link in navLinks" :key="link.name">
                        <router-link :to="link.path" class="navLink">
                            {{ link.name }}
                        </router-link>
                    </li>
                </ul>
            </div>
        </div>
        
        <div class="hamburgerMenu">
            <!-- HAMBURGER BUTTON (Hidden on Desktop) -->
            <button 
                class="hamburgerBtn" 
                @click="isMenuOpen = !isMenuOpen"
                aria-label="Toggle menu"
            >
                <img src="../assets/list.svg" alt="Menu" class="hamburgerIcon">
            </button>
        </div>

        <!-- MOBILE DROPDOWN -->
        <div class="mobileDropdown" :class="{ 'isOpen': isMenuOpen }">
            <div class="mobileDropdownInner">
                <ul>
                    <li v-for="link in navLinks" :key="link.name">
                        <router-link 
                            :to="link.path" 
                            @click="isMenuOpen = false"
                            class="mobileLink"
                        >
                            {{ link.name }}
                        </router-link>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</template>

<style scoped>
/* --- CONFIGURATION --- */
.navbar {
    --nav-bg: #222;
    --nav-text: #fff;
    --accent: orangered;
    --navbar-height: 70px;
    
    background-color: var(--nav-bg);
    color: var(--nav-text);
    height: var(--navbar-height);
    
    /* --- CHANGES FOR STICKY HEADER --- */
    position: fixed; /* Stick to the screen, not the page */
    top: 0;
    left: 0;
    width: 100%;     /* Ensure it spans the full width */
    z-index: 1000;   /* High number ensures it sits ON TOP of page content */
}

.navbarContainer {
    max-width: 1000px;
    height: 100%;
    margin: 0;
    padding: 0 1rem;
    display: flex;
    align-items: center;
    justify-content: space-between;
}

/* --- LOGO --- */
.logo img {
    height: 40px;
    width: auto;
    display: block;
    margin-right: 20px;
}

/* --- SHARED LINK STYLES --- */
.navLink, .mobileLink {
    text-decoration: none;
    color: var(--nav-text);
    transition: color 0.2s;
    font-size: 1rem;
}

/* Note: 'router-link-exact-active' is automatically generated by Vue Router and usually stays kebab-case unless configured otherwise in the router setup. */
.navLink.router-link-exact-active,
.mobileLink.router-link-exact-active {
    color: var(--accent);
    font-weight: bold;
}

/* =========================================
    MEDIA QUERIES
   ========================================= */

/* --- MOBILE VIEW (Width < 600px) --- */
@media (max-width: 600px) {
    .desktopMenu {
        display: none;
    }

    .hamburgerMenu {
        float: right; 
        margin-right: 20px;
        /* Float works here because it's outside the flex container, 
           though generally Flexbox is preferred for layout. */
    }

    .hamburgerBtn {
        display: block;
        background: none;
        border: none;
        cursor: pointer;
        padding: 5px;
    }

    .hamburgerIcon {
        width: 30px;
        height: 30px;
        filter: invert(1);
        display: block;
    }
}

/* --- DESKTOP VIEW (Width >= 601px) --- */
@media (min-width: 601px) {
    .hamburgerBtn, .mobileDropdown {
        display: none !important;
    }

    .desktopMenu {
        display: block;
    }

    .navList {
        display: flex;
        gap: 2rem;
        list-style: none;
        margin: 0;
        padding: 0;
    }
}

/* =========================================
    MOBILE DROPDOWN ANIMATION
   ========================================= */
.mobileDropdown {
    position: absolute;
    top: var(--navbar-height);
    left: 0;
    width: 100%;
    background-color: #333;
    
    display: grid;
    grid-template-rows: 0fr;
    transition: grid-template-rows 0.3s ease-out;
    
    box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
}

.mobileDropdown.isOpen {
    grid-template-rows: 1fr;
}

.mobileDropdownInner {
    overflow: hidden;
}

.mobileDropdown ul {
    list-style: none;
    margin: 0;
    padding: 0;
    display: flex;
    flex-direction: column;
}

.mobileLink {
    display: block;
    padding: 1.5rem;
    text-align: center;
    border-bottom: 1px solid #444;
    width: 100%;
}

.mobileLink:hover {
    background-color: #444;
}
</style>