# Generated by Django 6.0 on 2026-01-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done'), ('missed', 'Missed'), ('archived', 'Archived')], default='todo', max_length=15),
        ),
    ]
