# Generated by Django 5.2.9 on 2026-01-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
