# Generated by Django 5.2.8 on 2025-11-12 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0002_initial'),
        ('task', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assigned',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_UserId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachment',
            name='uploaded_by_userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_UserId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_UserId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to_userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assigned_UserId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by_userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_created_UserId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='groupid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_GroupId', to='group.group'),
        ),
        migrations.AddField(
            model_name='comment',
            name='taskid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_TaskId', to='task.task'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='taskid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_TaskId', to='task.task'),
        ),
        migrations.AddField(
            model_name='assigned',
            name='taskid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_TaskId', to='task.task'),
        ),
        migrations.AlterUniqueTogether(
            name='assigned',
            unique_together={('taskid', 'userid')},
        ),
    ]
