# Generated by Django 5.2.8 on 2025-11-12 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created_by_UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_created_UserId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group_members',
            name='groupid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_member_GroupId', to='group.group'),
        ),
        migrations.AddField(
            model_name='group_members',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_member_UserId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='group_members',
            unique_together={('groupid', 'userid')},
        ),
    ]
