# Generated by Django 5.2.8 on 2025-12-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='imageUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
