# Generated by Django 5.2.8 on 2025-12-09 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='imageUrl',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
