# Generated by Django 6.0 on 2026-01-20 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('operator', 'Operator'), ('moderator', 'Moderator'), ('leader', 'Leader')], default='member', max_length=10),
        ),
    ]
