# Generated by Django 6.0.1 on 2026-01-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_group_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('operator', 'Operator'), ('moderator', 'Moderator'), ('leader', 'Leader')], default='reader', max_length=10),
        ),
    ]
